=pod

=head1 Garden Design Software

=head2 Author

L<Ron Savage|http://savage.net.au/>, aka iFlower on L<the Flower Forums|http://www.flowersforums.com/forums/>.

=head2 Introduction

I'm close to releasing a free software package, written in L<Perl|https://www.perl.org/>, which will be
available from both L<my web site|http://savage.net.au/Perl-modules.html> and from my
L<public repository|https://metacpan.org/author/RSAVAGE>. The latter is hosted in Finland even though I
live in Melbourne, Australia.

This article discusses some details about the Search Engine component (see figure 1) of the package.

=head2 System Flowchart

=begin html

<table align = 'center' class = 'generic_border'>
	<tr>
		<td class = 'generic_border'>
			<table>
				<tr rowspan = '3'>
					<td>
						<br /><br /><br /><br />
						<span class = 'large_text'>Data about the flowers is manually entered into text files.</span>
						<br />
						<span class = 'large_text'>Text (*.csv) files were chosen so I could bootstrap the whole system.</span>
						<br />
						<span class = 'large_text'>Also, I'm hopeful we could build a communal database by sharing such files.</span>
						<br /><br />
					</td>
				</tr>
				<tr rowspan = '2'>
					<td>
						<br /><br /><br /><br /><br /><br />
						<span class = 'large_text'>The files are imported into a database<br />using the free program SQLite.</span>
						<br /><br />
						</td>
				</tr>
				<tr rowspan = '3'>
					<td>
						<br /><br />
						<span class = 'large_text'>(On the left) The Search Engine is discussed below.</span>
						<br />
						<span class = 'large_text'>(On the right) The Export code can re-create the *.csv files, and it can generate:</span>
						<br />
						<span class = 'large_text'>o The <a href = 'http://savage.net.au/Flowers.html'>Flower Catalog</a>,</span>
						<br />
						<span class = 'large_text'>o The <a href = 'http://savage.net.au/Flowers/front.garden.layout.html'>Front Garden Layout</a>, and</span>
						<br />
						<span class = 'large_text'>o The <a href = 'http://savage.net.au/Flowers/back.garden.layout.html'>Back Garden Layout</a>.</span>
						<br /><br />
						<span class = 'large_text'>Each flower has its own page, and all such pages<br />are pointed to by the Catalog and the Layouts</span>
						<br />
						<span class = 'large_text'>via clickable thumbnail images.</span>
					</td>
				</tr>
			</table>
		</td>
		<td class = 'generic_border'>
			<table>
				<tr>
					<td rowspan = '8'>
						<img src = 'http://savage.net.au/Perl-modules/html/garden.design/Garden.Design.Software.figure.1.svg'>
					</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td></td>
		<td align = 'center'>
			<br /><br />
			<span class = 'large_text'>Figure 1 - The System Flowchart</span>
		</td>
	</tr>
</table>

=end html

=head2 So, what is this Search Engine?

Here, we step thru the process of searching, and viewing the search results.

Notes:

=over 4

=item o These screenshots were rigged for clarity by using a very large font

=item o The Objects and Design tabs don't do anything yet

=back

=begin html

<table align = 'center' class = 'generic_border'>
	<tr>
		<td><img src = '/Perl-modules/html/garden.design/Search.Engine.Screenshot.1.jpg'></td>
	</tr>
	<tr>
		<td align = 'center'>
			<br />
			<span class = 'large_text'>Figure 2 - The Default Search Screen</span>
			<br /><br /><br /><hr /><hr />
		</td>
	</tr>
	<tr>
		<td><img src = '/Perl-modules/html/garden.design/Search.Engine.Screenshot.2.jpg'></td>
	</tr>
	<tr>
		<td align = 'center'>
			<br />
			<span class = 'large_text'>Figure 3 - Search Results after typing in 'chor'</span>
			<br /><br /><br /><hr /><hr />
		</td>
	</tr>
	<tr>
		<td><img src = '/Perl-modules/html/garden.design/Search.Engine.Screenshot.3.jpg'></td>
	</tr>
	<tr>
		<td align = 'center'>
			<br />
			<span class = 'large_text'>Figure 4 - The Flower Tab (After clicking on the first result's thumbnail)</span>
			<br />
			<span class = 'large_text'>Upon that click the 5 sub-tabs 'Flower' to 'URLs' are filled in automatically</span>
			<br /><br /><br /><hr /><hr />
		</td>
	</tr>
	<tr>
		<td><img src = '/Perl-modules/html/garden.design/Search.Engine.Screenshot.4.jpg'></td>
	</tr>
	<tr>
		<td align = 'center'>
			<br />
			<span class = 'large_text'>Figure 5 - The Attributes Tab</span>
			<br /><br /><br /><hr /><hr />
		</td>
	</tr>
	<tr>
		<td><img src = '/Perl-modules/html/garden.design/Search.Engine.Screenshot.5.jpg'></td>
	</tr>
	<tr>
		<td align = 'center'>
			<br />
			<span class = 'large_text'>Figure 6 - The Images Tab</span>
			<br /><br /><br /><hr /><hr />
		</td>
	</tr>
	<tr>
		<td><img src = '/Perl-modules/html/garden.design/Search.Engine.Screenshot.6.jpg'></td>
	</tr>
	<tr>
		<td align = 'center'>
			<br />
			<span class = 'large_text'>Figure 7 - The Notes Tab</span>
			<br /><br /><br /><hr /><hr />
		</td>
	</tr>
	<tr>
		<td><img src = '/Perl-modules/html/garden.design/Search.Engine.Screenshot.7.jpg'></td>
	</tr>
	<tr>
		<td align = 'center'>
			<br />
			<span class = 'large_text'>Figure 8 - The URLs Tab</span>
		</td>
	</tr>
</table>

=end html

=head2 Contents of the Package

=over 4

=item o The Source Code

Yes. Being a standard Perl package (aka distro) you get the source code of every component. This includes
the source code of various small Perl programs, each just a few hundred bytes in size.

There are no pre-compiled - and hence unreadable - components, such as *.exe files, which you might be used to
downloading.

=item o A Set of *.csv Files

The package includes a set of *.csv (L<Comma-Separated Variables|https://en.wikipedia.org/wiki/Comma-separated_values>)
text files containing details of the plants in my garden. These files are imported into the database to bootstrap the
system. The package also includes an export component which generates these:

Since these files only contain partial information on my flowers, I'm hoping you can either show me a public
database of flower data I can incorporate into my package, and thereby ship to all those who download my program,
or perhaps everyone using the program can enter the details of a few flowers, and I can combine all your data
into a new database for another free download.

=over 4

=item o The Flower Catalog

This is a HTML table which the code can incorporate into a stand-alone page, or which can be embedded
in another web page, L<as I do here|http://savage.net.au/Flowers.html>.

=item o A Set of Garden Layout Pages

In this case the output is one *.svg (L<Scalable Vector Graphics|https://en.wikipedia.org/wiki/Scalable_Vector_Graphics>)
image for each garden. Here they are for L<my front garden|http://savage.net.au/Flowers/front.garden.layout.html>
and for L<my back garden|http://savage.net.au/Flowers/back.garden.layout.html>.

=back

=item o Various other data files

One of these is the database produced by the import component, and with which all other components interact.

=item o A Search Engine

Yes - You get a serch engine specifically written to work with the database.

=item o The source files which make up this article, including the images

The image is shipped with the package as html/Garden.Design.Software.figure.1.svg, and the file which is
converted into that image is shipped as html/Garden.Design.Software.figure.1.dash. See
scripts/Garden.Design.Software.sh for the conversion process.

=back
