=pod

=head1 Garden Design Software

=head2 Overview

=begin html

<table align = 'center'>
	<tr><td>
		<img src = 'http://savage.net.au/Perl-modules/html/garden.design/block.diagram.svg'>
	</td></tr>
</table>

=end html

The file which is converted into the above image is shipped in html/block.diagram.dash.
